[package]
name = "veritix-contract"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
crate-type = ["cdylib"]
doctest = false

[dependencies]
soroban-sdk = "27.0.3"

[dev-dependencies]
soroban-sdk = { version = "27.0.3", features = ["testutils"] }

[features]
default = []
testutils = ["soroban-sdk/testutils"]